FROM python:3.7.3-stretch

COPY ingestor/requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

COPY common/*.py /home/appuser/python/common/
COPY ingestor/*.py /home/appuser/python/ingestor/

#TODO - Add worker processes to gunicorn below 
CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "--pythonpath", "/home/appuser/python/ingestor", "wsgi" ]