FROM python:3.7.3-stretch

COPY form_handler/requirements.txt /tmp/

RUN pip install pip -U
RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

ENV PYTHONPATH /home/appuser/

COPY common/ /home/appuser/python/common/
COPY form_handler/ /home/appuser/python/form_handler/

CMD [ "python", "./python/form_handler/listener.py" ]
