FROM python:3.7.3-stretch

COPY validator/requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

COPY common/*.py /home/appuser/common/
COPY validator/*.py /home/appuser/
COPY validator/*.json /home/appuser/

CMD [ "python", "./listener.py" ]
