FROM python:3.7.3-stretch

COPY geocoder/requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

COPY common/*.py /home/appuser/python/common/
COPY geocoder/*.py /home/appuser/python/geocoder/

#TODO - Add worker processes to gunicorn below 
CMD [ "gunicorn", "--bind", "0.0.0.0:5003", "--pythonpath", "/home/appuser/python/geocoder", "wsgi" ]