FROM python:3.7.3-stretch

COPY form_verifier/requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

ENV PYTHONPATH /home/appuser/

COPY common/ /home/appuser/python/common/
COPY form_verifier/ /home/appuser/python/form_verifier/

CMD [ "python", "./python/form_verifier/listener.py" ]
