FROM nginx:latest

RUN useradd --create-home appuser
RUN ["mkdir", "/app"]
WORKDIR /app

COPY nginx.conf /app/nginx.conf
COPY dist /app/dist

CMD ["nginx-debug", "-c", "/app/nginx.conf",  "-g", "daemon off;"]

