FROM python:3.7.3-stretch

COPY paybc_api/requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser

COPY common /home/appuser/python/common
COPY paybc_api /home/appuser/python/paybc_api

RUN ["python", "-m", "pytest"]

CMD [ "gunicorn", "--bind", "0.0.0.0:5001", "--pythonpath", "/home/appuser/python/paybc_api", "wsgi:create_app()" ]