# This test script is for Visual Studio Code and the HTTP Client plugin.
#
#  ____  _____ _    ____ ___ 
# |  _ \|  ___/ \  |  _ \_ _|
# | | | | |_ / _ \ | |_) | | 
# | |_| |  _/ ___ \|  __/| | 
# |____/|_|/_/   \_\_|  |___|

# Wiki for DFAPI testing:      https://justice.gov.bc.ca/wiki/pages/viewpage.action?pageId=257917165&src=contextnavpagetreemode
# Expected fields and values:  https://justice.gov.bc.ca/wiki/display/RDFP/DFAPI:+submission+fields+and+expected+values
# ORDS endpoint documentation: https://justice.gov.bc.ca/wiki/display/RDFP/Digital+Forms+API:+ORDS+helper+endpoints


# TEST
# ====
#  $ oc project be78d6-test
#  $ oc rsh svc/rsbc-dh-form-handler-test
# PROD
#  $ oc --namespace=be78d6-prod rsh svc/rsbc-dh-form-handler-prod


#  ____  _______     __
# |  _ \| ____\ \   / /
# | | | |  _|  \ \ / / 
# | |_| | |___  \ V /  
# |____/|_____|  \_/   

# NOTE: If you need a new IRP number, create one in VIPS DEV at https://dev.justice.gov.bc.ca/vips/prohibitions/new
# ====
  # oc project be78d6-dev
  # oc --namespace=be78d6-dev rsh svc/rsbc-dh-form-handler-dev
# Get credentials from DF DEV pod:
  # oc --namespace=be78d6-dev exec svc/rsbc-dh-form-handler-dev -- sh -c 'echo ${VIPS_API_USERNAME}'
  # oc --namespace=be78d6-dev exec svc/rsbc-dh-form-handler-dev -- sh -c 'echo ${VIPS_API_PASSWORD}'
# Get DFAPI credentials from the DFAPI DEV pod:
  # oc --namespace=c220ad-dev describe secret digitalforms-api
  # $USERNAME64 = oc --namespace=c220ad-dev get secret digitalforms-api -o jsonpath="{.data.DIGITALFORMS_BASICAUTH_USER}"
  # $PASSWORD64 = oc --namespace=c220ad-dev get secret digitalforms-api -o jsonpath="{.data.DIGITALFORMS_BASICAUTH_PASSWORD}"
  # $USERNAME   = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String(${USERNAME64}))
  # $PASSWORD   = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String(${PASSWORD64}))
# Get DFAPI pod log
  # oc --namespace=c220ad-dev logs svc/digitalforms-api 
  # oc --namespace=c220ad-dev logs svc/digitalforms-api --follow --since=1s


# Test prohibitions
# | Type | Notice number | Prohibition id |
# |------+---------------+----------------|
# | ADP  |      21900069 |            168 |
# | ADP  |      21900104 |            182 |
# | IRP  |      21900050 |            133 |
# | IRP  |      21900051 |            134 |
# | UL   |      21900307 |            205 |
# | UL   |      21900308 |            214 |
# | UL   |      30444445 |                | Completed review by Eric Mills 
#
# NOTE: Prohibitions created in DFAPI DEV environment do not show up in VIPS DEV environment, and vice-versa.

# # ORDS (used to reset test records)
@ORDS_DELETE_APPLICATION_URL_OLD = dev.jag.gov.bc.ca/ords/deva/rsdfrmords/web/digitalForm/prohibition
@ORDS_DELETE_APPLICATION_URL =     dev.jag.gov.bc.ca/ords/devh/rsdfrmords/web/digitalForm/prohibition
@ORDS_HEALTHCHECK_URL =            dev.jag.gov.bc.ca/ords/devh/rsdfrmords/web/health 
@ORDS_DELETE_APPLICATION_AUTH =    rsdfrm_dev:Welc0me!@
@ORDS_DELETE_REVIEW_TIME_URL_OLD = dev.jag.gov.bc.ca/ords/dev/vipsords/web/prohibition
@ORDS_DELETE_REVIEW_TIME_URL =     dev.jag.gov.bc.ca/ords/devh/vipsords/web/prohibition

# # DFAPI
@DFAPI_URL =                       digitalforms-api.c220ad-dev.svc/digitalforms
@DFAPI_CREDENTIALS =               user:QvJXyT!Vp48ax=vN

# # ADP prohibition
@FORM_TYPE =                   ADP
@NOTICE_NUMBER  =              00198501
@PROHIBITION_ID =              3639
@DOCUMENT_ID =                 497
@PRESENTATION_TYPE =           WRIT
#                              Valid for ADP: ORAL, WRIT, CANCELLED, NONE
@REVIEW_ROLE_TYPE =            AUTHPERS
#                              Valid: APPNT, LWYR, AUTHPERS

#IRP prohibition
# @FORM_TYPE =                   IRP
# @NOTICE_NUMBER  =              21900051
# @PROHIBITION_ID =              134
# @DOCUMENT_ID =                 497
# @PRESENTATION_TYPE =           WRIT
# #                              Valid for IRP: ORAL, WRIT, CANCELLED, NONE
# @REVIEW_ROLE_TYPE =            APPNT
# #                              Valid: APPNT, LWYR, AUTHPERS

# # UL prohibition
# @FORM_TYPE =                   UL
# @NOTICE_NUMBER  =              30444445
# @PROHIBITION_ID =              214
# @DOCUMENT_ID =                 497
# @PRESENTATION_TYPE =           WRIT
# #                              Valid for UL: WRIT, CANCELLED, NONE
# @REVIEW_ROLE_TYPE =            APPNT
# #                              Valid: APPNT, LWYR, AUTHPERS

@CORRELATION =                 saf-{{FORM_TYPE}}-{{PROHIBITION_ID}}-{{NOTICE_NUMBER}}



#  _____ _____ ____ _____ 
# |_   _| ____/ ___|_   _|
#   | | |  _| \___ \ | |  
#   | | | |___ ___) || |  
#   |_| |_____|____/ |_|  

# NOTE: If you need a new IRP number, create one in VIPS DEV at https://test.justice.gov.bc.ca/vips/prohibitions/new

  # | Type | Notice number | Prohibition id | GUID                                 | disclosure documents |
  # |------+---------------+----------------+--------------------------------------+----------------------|
  # | ADP  |      00810088 |           4364 | b3db314d-a770-0f18-e054-00144ff84cea | 1035, 1031           |
  # | ADP  |      00810080 |           4363 |                                      | 1026, 1023           |
  # | IRP  |      21999994 |           4497 | ae84d95d-53b2-0c72-e054-00144ff84cea | 987, 985             |
  # | IRP  |      21884488 |           4428 |                                      | 1036, 986            |
  # | UL   |      30100102 |           4118 | ae84d95d-53b3-0c72-e054-00144ff84cea |                      |
  # | UL   |      30100101 |           4117 |                                      |                      |

  # @ORDS_DELETE_APPLICATION_URL =  test.jag.gov.bc.ca/ords/tsth/rsdfrmords/web/digitalForm/prohibition
  # @ORDS_DELETE_APPLICATION_AUTH = rsdfrm_test:Welc0me2!
  # @ORDS_DELETE_REVIEW_TIME_URL =  test.jag.gov.bc.ca/ords/tsth/vipsords/web/prohibition
  # @ORDS_HEALTHCHECK_URL =         test.jag.gov.bc.ca/ords/tsth/rsdfrmords/web/health 
  # # DFAPI TEST server
  # @DFAPI_URL =                    digitalforms-api.c220ad-test.svc/digitalforms
  # @DFAPI_CREDENTIALS =             user:SfUMGE+E.SaxhP=t


  # # ADP prohibition
  # @FORM_TYPE =                   ADP
  # @NOTICE_NUMBER  =              00810088
  # @PROHIBITION_ID =              4364
  # @DOCUMENT_ID =                 1035
  # @PRESENTATION_TYPE =           WRIT
  # #                              Valid for ADP: ORAL, WRIT, CANCELLED, NONE
  # @REVIEW_ROLE_TYPE =            APPNT
  # #                              Valid: APPNT, LWYR, AUTHPERS
  # @application_id =              d5f6c461-5839-52cb-e054-00144ffb2e6c

  # # IRP prohibition
  # @FORM_TYPE =                   IRP
  # @NOTICE_NUMBER  =              21197507
  # @PROHIBITION_ID =              5475
  # @DOCUMENT_ID =                 1723
  # @PRESENTATION_TYPE =           WRIT
  # #                              Valid for IRP: ORAL, WRIT, CANCELLED, NONE
  # @REVIEW_ROLE_TYPE =            APPNT
  #  #                             Valid: APPNT, LWYR, AUTHPERS
  # @application_id =              d5f6c461-583c-52cb-e054-00144ffb2e6c

  # # UL prohibition
  # @FORM_TYPE =                   UL
  # @NOTICE_NUMBER  =              30197506
  # @PROHIBITION_ID =              5508
  # @DOCUMENT_ID =                 1724
  # @PRESENTATION_TYPE =           WRIT
  # #                              Valid for UL: WRIT, CANCELLED, NONE
  # @REVIEW_ROLE_TYPE =            APPNT
  # #                              Valid: APPNT, LWYR, AUTHPERS
  # @application_id =              eb806480-aa50-6f94-e054-00144ffb2e6c

  # # Needed by all application types
  # @CORRELATION =                 saf-{{FORM_TYPE}}-{{PROHIBITION_ID}}-{{NOTICE_NUMBER}}


# ____  ____   ___  ____
# |  _ \|  _ \ / _ \|  _ \
# | |_) | |_) | | | | | | |
# |  __/|  _ <| |_| | |_| |
# |_|   |_| \_\\___/|____/

# NOTE: BE CAREFUL!

  # @ORDS_DELETE_APPLICATION_URL =  jag.gov.bc.ca/ords/prodh/rsdfrmords/web/digitalForm/prohibition
  # @ORDS_DELETE_APPLICATION_AUTH = rsdfrm_prod:W3lc0me245!
  # @ORDS_DELETE_REVIEW_TIME_URL =  jag.gov.bc.ca/ords/prodh/vipsords/web/prohibition
  # @ORDS_HEALTHCHECK_URL =         jag.gov.bc.ca/ords/prodh/rsdfrmords/web/health 
  # # DFAPI TEST server
  # @DFAPI_URL =                    digitalforms-api-c220ad-prod.apps.silver.devops.bcgov/digitalforms
  # @DFAPI_CREDENTIALS =            dfuser_prod:eAkt#62/8E(7eaS!


  # ADP prohibition
  # @FORM_TYPE =                   ADP
  # @NOTICE_NUMBER  =              00810088
  # @PROHIBITION_ID =              4364
  # @DOCUMENT_ID =                 1035
  # @PRESENTATION_TYPE =           WRIT
  # #                              Valid for ADP: ORAL, WRIT, CANCELLED, NONE
  # @REVIEW_ROLE_TYPE =            APPNT
  # #                              Valid: APPNT, LWYR, AUTHPERS
  # @application_id =              d5f6c461-5839-52cb-e054-00144ffb2e6c

  # # IRP prohibition
  # @FORM_TYPE =                   IRP
  # @NOTICE_NUMBER  =              21197507
  # @PROHIBITION_ID =              5475
  # @DOCUMENT_ID =                 1723
  # @PRESENTATION_TYPE =           WRIT
  # #                              Valid for IRP: ORAL, WRIT, CANCELLED, NONE
  # @REVIEW_ROLE_TYPE =            APPNT
  #  #                             Valid: APPNT, LWYR, AUTHPERS
  # @application_id =              d5f6c461-583c-52cb-e054-00144ffb2e6c

  # # UL prohibition
  # @FORM_TYPE =                   UL
  # @NOTICE_NUMBER  =              ________
  # @PROHIBITION_ID =              5508
  # @DOCUMENT_ID =                 1724
  # @PRESENTATION_TYPE =           WRIT
  # #                              Valid for UL: WRIT, CANCELLED, NONE
  # @REVIEW_ROLE_TYPE =            APPNT
  # #                              Valid: APPNT, LWYR, AUTHPERS
  # @application_id =              eb806480-aa50-6f94-e054-00144ffb2e6c

  # # Needed by all application types
  # @CORRELATION =                 saf-{{FORM_TYPE}}-{{PROHIBITION_ID}}-{{NOTICE_NUMBER}}


#### SET GUID APPLICATION ID
############################

######################################################

### GET SWAGGER OPENAPI

GET http://{{DFAPI_URL}}/v2/api-docs


### ORDS HEALTHCHECK
####################################
GET https://{{ORDS_HEALTHCHECK_URL}}


### DELETE PROHIBITION REVIEW APPLICATION (alternative method, using authentication)
### NOTE: You should not need to use this. It doesn't seem to work any more. No auth is
### Required in the DEV or TEST environment, as per Kyle Flood, 2022-06-10.
####################################################################################
# Must be connected to VPN unless running on OpenShift pod.
# Example : https://wsgw.dev.jag.gov.bc.ca/rsdfrm/ords/deva/rsdfrmords/web/digitalForm/prohibition/134/222
# NOTE: If the correlation id does not start with a number, you will get an error page. The correlation id must be unique for ORDS calls.
#DELETE https://{{ORDS_DELETE_APPLICATION_URL}}/{{PROHIBITION_ID}}/222
#Authorization: Basic {{ORDS_DELETE_APPLICATION_AUTH}}
#Accept: */*



### DELETE PROHIBITION REVIEW APPLICATION (no authentication)
#############################################################
# Must be connected to VPN unless running on OpenShift pod.
# Steve's: DELETE https://dev.jag.gov.bc.ca/ords/deva/rsdfrmords/web/digitalForm/prohibition/182/333
# NOTE: If the correlation id does not start with a number, you will get an error page. The correlation id must be unique for ORDS calls.
DELETE https://{{ORDS_DELETE_APPLICATION_URL}}/{{PROHIBITION_ID}}/333




### DELETE SCHEDULED REVIEWS (no authentication)
################################################
# Must be connected to VPN unless running on OpenShift pod.
# Example: DELETE https://dev.jag.gov.bc.ca/ords/deva/vipsords/web/prohibition/21900104/review/schedule/ADP/saf1234
DELETE https://{{ORDS_DELETE_REVIEW_TIME_URL}}/{{NOTICE_NUMBER}}/review/schedule/{{FORM_TYPE}}/{{application_id}}




### CREATE NEW PROHIBITION REVIEW APPLICATION
#############################################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: POST http://wsgw.dev.jag.gov.bc.ca/digitalforms/ADP/21900104/application/saf1044
@correlation_id = {{CORRELATION}}-3003
POST http://{{DFAPI_URL}}/{{FORM_TYPE}}/{{NOTICE_NUMBER}}/application/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json

{
  "applicationInfo": {
    "email": "steve.1.forsyth@gov.bc.ca",
    "faxNo": "2501112222",
    "firstGivenNm": "Steve",
    "formData": "JVBERi0xLjIgCjkgMCBvYmoKPDwKPj4Kc3RyZWFtCkJULyA5IFRmKFRlc3QpJyBFVAplbmRzdHJlYW0KZW5kb2JqCjQgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCA1IDAgUgovQ29udGVudHMgOSAwIFIKPj4KZW5kb2JqCjUgMCBvYmoKPDwKL0tpZHMgWzQgMCBSIF0KL0NvdW50IDEKL1R5cGUgL1BhZ2VzCi9NZWRpYUJveCBbIDAgMCA5OSA5IF0KPj4KZW5kb2JqCjMgMCBvYmoKPDwKL1BhZ2VzIDUgMCBSCi9UeXBlIC9DYXRhbG9nCj4+CmVuZG9iagp0cmFpbGVyCjw8Ci9Sb290IDMgMCBSCj4+CiUlRU9G",
    "manualEntryYN": "N",
    "noticeSubjectCd": "PERS",
    "phoneNo": "2501113333",
    "presentationTypeCd": "{{PRESENTATION_TYPE}}",
    "reviewRoleTypeCd": "{{REVIEW_ROLE_TYPE}}",
    "secondGivenNm": "Two",
    "surnameNm": "Lungpayne"
  }
}

### APPLICATION ID RETURNED FROM FORM CREATION ENDPOINT ABOVE
#############################################################
# 1st: 
@application_id =               f27b9894-7428-611e-e054-00144ffbc109
# # 2nd:
#@application_id =              d5f6c461-5842-52cb-e054-00144ffb2e6c
# 3rd:
# #@application_id =              d5066135-bf2e-4c55-e054-00144ffb2e6c




### GET PROHIBITION REVIEW APPLICATION
######################################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: http://digitalforms-api.c220ad-dev.svc/digitalforms/c741582c-de28-67e2-e054-00144ffbc109/application/saf-ADP-182-21900104-3004
@correlation_id = {{CORRELATION}}-3004

GET http://{{DFAPI_URL}}/{{application_id}}/application/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json



### PATCH PROHIBITION REVIEW APPLICATION
########################################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: 
@correlation_id = {{CORRELATION}}-3005

PATCH http://{{DFAPI_URL}}/{{FORM_TYPE}}/{{application_id}}/application/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json

{
  "applicationInfo": {
    "faxNo": "9999999999",
    "phoneNo": "8888888888"
  }
}



### QUERY PROHIBITION STATUS
############################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: http://digitalforms-api.c220ad-dev.svc/digitalforms/21900104/status/saf-ADP-182-21900104-3006

@correlation_id = {{CORRELATION}}-3006
GET http://{{DFAPI_URL}}/{{NOTICE_NUMBER}}/status/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json



### GET DISCLOSURE
##################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: GET http://digitalforms-api.c220ad-dev.svc/digitalforms/20/disclosure/saf-ADP-182-21900104-3007

@correlation_id = {{CORRELATION}}-3007
GET http://{{DFAPI_URL}}/{{DOCUMENT_ID}}/disclosure/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json



### MARK DISCLOSURE DOCUMENT AS SENT
####################################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: PATCH http://digitalforms-api.c220ad-dev.svc/digitalforms/disclosure/saf-ADP-182-21900104-3008

@correlation_id = {{CORRELATION}}-3008
PATCH http://{{DFAPI_URL}}/disclosure/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json

{
  "disclosure": {
    "disclosedDtm": "{{$datetime "YYYY-MM-DD HH:mm:ss -00:00"}}",
    "documentId": "{{DOCUMENT_ID}}"
  }
}


# >>> DISCLOSURE CHECK <<<
# -----------------------------------------------------------------------------------------------
# Check that disclosure has happened by looking at the response from the QUERY endpoint.
# When a disclosure has not been sent, you should see the "disclosure" element prohibition query
# responses with no date. For example: 
#   "disclosure":[{"documentId":"1600"}]
# After the disclosure, the date is added, like this:
#   "disclosure":[{"documentId":"1600","disclosedDtm":"2021-12-20 09:41:25 -08:00"}]
# -----------------------------------------------------------------------------------------------


### GET PAYMENT STATUS
######################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: http://digitalforms-api.c220ad-dev.svc/digitalforms/c741582c-de28-67e2-e054-00144ffbc109/payment/status/saf-ADP-182-21900104-3009
# NOTE: an HTTP 404 response with "Requested data not found" means that no payment has been made.

@correlation_id = {{CORRELATION}}-3009

GET http://{{DFAPI_URL}}/{{application_id}}/payment/status/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json


### PATCH PAYMENT
################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: http://digitalforms-api.c220ad-dev.svc/digitalforms/c741582c-de28-67e2-e054-00144ffbc109/payment/saf-ADP-182-21900104-3010
# NOTE: receipt number must be unique
@correlation_id = {{CORRELATION}}-3010
PATCH http://{{DFAPI_URL}}/{{application_id}}/payment/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json

{
  "transactionInfo":
  {
    "paymentAmount":"200.00",
    "paymentCardType":"VISA",
    "paymentDate":"{{$datetime "YYYY-MM-DD HH:mm:ss -00:00"}}",
    "receiptNumberTxt":"{{$randomInt 90000000 99999999}}"
  }
}

# >>> PAYMENT CHECK <<<
# -----------------------------------------------------------------------------------------------
# Check that payment has happened by looking at the response from the GET PAYMENT STATUS endpoint.
# You should also see the receipt number from the QUERY STATUS endpoint.
#
# **NOTE**: The payment receipt number must be unique. That's why it's generated with a random int
# in the PATCH PAYMENT request above. If it's not unique, the payment will fail.
#
# When a payment has not been sent, you should see an empty "transactionInfo" element in the GET PAYMENT
# response. For example: 
#   "transactionInfo": {}
# After payment, the date is added, like this:
#    "transactionInfo":{"paymentCardType":"VISA","paymentAmount":"200.00","receiptNumberTxt":"90320189","paymentDate":"2022-01-07 15:13:48 -08:00"}
# The status endpoint shows the receipt number likes this:
#    "reviews":[{"applicationId":"d5066135-bf27-4c55-e054-00144ffb2e6c","receiptNumberTxt":"96237001"}]
# -----------------------------------------------------------------------------------------------


### GET REVIEW SCHEDULE
#######################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: http://digitalforms-api.c220ad-dev.svc/digitalforms/ADP/ORAL/2021-07-16/review/availableTimeSlot/saf-ADP-182-21900104-3011
# Note: there should be no reviews on the weekends. Days with no reviews available return an HTTP 404.
@correlation_id = {{CORRELATION}}-3011

GET http://{{DFAPI_URL}}/{{FORM_TYPE}}/{{PRESENTATION_TYPE}}/{{$datetime "YYYY-MM-DD" 4 d}}/review/availableTimeSlot/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json



### SCHEDULE A REVIEW
#####################
# Disconnect from VPN to run this command, or run on OpenShift pod.
# Example: http://digitalforms-api.c220ad-dev.svc/digitalforms/c741582c-de28-67e2-e054-00144ffbc109/review/schedule/saf-ADP-182-21900104-3012
@correlation_id = {{CORRELATION}}-3012

POST http://{{DFAPI_URL}}/{{application_id}}/review/schedule/{{correlation_id}}
Authorization: Basic {{DFAPI_CREDENTIALS}}
Content-Type: application/json
Accept: application/json

{
  "timeSlot":
  {
    "reviewStartDtm":"2022-10-24 09:00:00 -07:00",
    "reviewEndDtm":"2022-10-24 09:30:00 -07:00"
  }
}

# >>> REVIEW CHECK <<<
# -----------------------------------------------------------------------------------------------
# Check that review is booked by looking at the response from the QUERY endpoint.
# When no review is scheduled, you should see the "reviews" element prohibition query
# responses with no dates. For example: 
#   "reviews": [{"applicationId":"d5066135-bf23-4c55-e054-00144ffb2e6c"}]
# After payment, the "reviewStartDtm" and "reviewEndDtm" elements are added, like this:
#    "reviews": [{"applicationId":"d5066135-bf23-4c55-e054-00144ffb2e6c","status":"in_progress","reviewStartDtm":"2022-01-11 09:30:00 -08:00","reviewEndDtm":"2022-01-11 10:00:00 -08:00","receiptNumberTxt":"90320189","reviewId":"4010"}
# -----------------------------------------------------------------------------------------------


### Now what?
#
# - Use the VIPS web front-end to mark the application as complete. Mark the review as unsuccessful. Check status.
# - Attempt to submit a new application for the same prohibition. 
#
#   **NOTE**: A second application should not work for ADP or IRP, but a UL prohibition is allowed to have a second review request. However, as of VIPS API 1.1.0, the VIPS API does allow ADP and UL prohibitions to be submitted again. After a discussion with Jonathan Longe in fall of 2021, we decided that it will not be possible for an applicant to submit a second application anyway, because the Digital Forms application system will check to see if an application already exists for each prohibition, and it will not attempt to create a second prohibition through the DFAPI anyway. So even though this is probably a defect in the DFAPI, it should never cause a problem.