	FROM python:3.7.3-stretch

	COPY /ingestor/requirements.txt /tmp/

	RUN pip install --upgrade pip
	RUN pip install -r /tmp/requirements.txt

	RUN useradd --create-home appuser
	WORKDIR /home/appuser
	USER appuser

	COPY /common /home/appuser/python/common
	COPY /ingestor /home/appuser/python/ingestor

	EXPOSE 5000

	# Comment out the tests for the time being. 
	#RUN ["python", "-m", "pytest"]  

	#Add worker processes to gunicorn below 
	CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "--pythonpath", "/home/appuser/python/ingestor", "wsgi" ]