FROM python:3.7.3-stretch

COPY hold_processor/requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

ENV PYTHONPATH /home/appuser/

COPY common/ /home/appuser/python/common/
COPY hold_processor/ /home/appuser/python/hold_processor/

CMD [ "python", "./python/hold_processor/script.py" ]
