import pytest
import python.writer.middleware as middleware


address_sample_data = [
    ["914 Yates Street", "914 Yates Street, BC"],
    ["E/B 914 Yates Street", "914 Yates Street, BC"],
    ["HWY # 1 / CLEARBROOK ON RAMP, ABBOTSFORD", "TRANS-CANADA HWY AND CLEARBROOK ON RAMP, ABBOTSFORD, BC"],
    ["HWY ONE - WELLSWOOD RD, MALAHAT", "TRANS-CANADA HWY AND WELLSWOOD RD, MALAHAT, BC"],
    ["HWY 97N AT HOFERKAMP, PRINCE GEORGE", "HWY-97 AND HOFERKAMP, PRINCE GEORGE, BC"],
    ["1100 BLK HIGHWAY ONE, SAANICH", "1100 TRANS-CANADA HWY, SAANICH, BC"],
    ["BLANSHARD ST SOUTH OF FINLAYSON, VICTORIA", "BLANSHARD ST AND FINLAYSON, VICTORIA, BC"],
    ["HWY 17 N/O ELK LAKE DR, SAANICH", "HWY-17 AND ELK LAKE DR, SAANICH, BC"],
    ["HWY 97SOUTH / BOYKO RD, PRINCE GEORGE", "HWY-97 AND BOYKO RD, PRINCE GEORGE, BC"],
    ["1200  HWY 16 E, PRINCE GEORGE", "1200 HWY-16 PRINCE GEORGE, BC"],
    ["ISLAND HWY / ATKINS RD, COLWOOD", "ISLAND HWY AND ATKINS RD, COLWOOD, BC"],
    ["HWY 97 NEAR ROCKY FSR, BEAR LAKE", "HWY-97 AND ROCKY FSR, BEAR LAKE, BC"],
    ["HIGHWAY #1 W/B NEAR WESTVIEW DR, NORTH VANCOUVER", "TRANS-CANADA HWY AND WESTVIEW DR, NORTH VANCOUVER, BC"],
    ["7200 BLK OF HWY 17, DELTA", "7200 HWY-17, DELTA, BC"],
    ["7200 BLOCK OF HWY 17, DELTA", "7200 HWY-17, DELTA, BC"],
    ["3600 BLK HWY 17 E/B, DELTA", "3600 HWY-17 DELTA, BC"],
    ["HWY 17 6400 BLK, DELTA", "6400 HWY-17 DELTA, BC"],
    ["3100 BLK MCGILL ST WESTBOUND, VANCOUVER", "3100 MCGILL ST VANCOUVER, BC"],
    ["3100 BLK MCGILL ST WEST BOUND, VANCOUVER", "3100 MCGILL ST VANCOUVER, BC"],
    ["MT SEYMOUR PKWY ON RAMP TO HWY 1 WB, NORTH VANCOUVER", "MT SEYMOUR PKWY AND TRANS-CANADA HWY NORTH VANCOUVER, BC"],
    ["MT SEYMOUR PKWY ONRAMP TO HWY 1 WB, NORTH VANCOUVER", "MT SEYMOUR PKWY AND TRANS-CANADA HWY NORTH VANCOUVER, BC"],
    ["MT SEYMOUR PKWY OFF RAMP TO HWY 1 WB, NORTH VANCOUVER", "MT SEYMOUR PKWY AND TRANS-CANADA HWY NORTH VANCOUVER, BC"],
    ["HWY 1, EAST, 200 ST, LANGLEY", "TRANS-CANADA HWY AND 200 ST, LANGLEY, BC"],
    ["HWY ONE, MALAHAT, 200 BLK", "200 TRANS-CANADA HWY, MALAHAT, BC"],
    ["HIGHWAY 91 ON RAMP FROM HIGHWAY 10 S/B, SURREY", "HWY-91 AND HWY-10 SURREY, BC"],
    ["16TH AVE / 25300 BLOCK, LANGLEY", "25300 16TH AVE AND LANGLEY, BC"],
    ["HWY 1 (300 BLK), MALAHAT", "300 TRANS-CANADA HWY MALAHAT, BC"],
    ["HIGHWAY 1 (EASTBOUND #3 RD), ABBOTSFORD", "TRANS-CANADA HWY ( 3 RD), ABBOTSFORD, BC"],
    ["HWY 99(NB) / SWIFT CREEK FSR, SQUAMISH", "HWY-99 AND SWIFT CREEK FSR, SQUAMISH, BC"]
]


@pytest.mark.parametrize("address_in, expected_output", address_sample_data)
def test_clean_address_method(address_in, expected_output):
    data = {"address_raw": address_in}
    is_success, data = middleware.clean_up_address(**data)
    assert data['address_clean'] == expected_output
