apiVersion: v1
kind: Template
metadata:
  name: rsbcdh-secrets-template
  annotations:
    description: "Create secret object for RSBC DH"
    tags: rabbitmq,mq,messaging
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: ${NAME}${SUFFIX}
      shared: "true"
    annotations:
      as-copy-of: "template.${NAME}"
    name: ${NAME}
  stringData:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    db-username: ${DB_USERNAME}
    db-password: ${DB_PASSWORD}
  type: Opaque
parameters:
- name: NAME
  displayName: "Name"
  description: "The name assigned to all of the OpenShift resources associated to the server instance."
  required: true
  value: "rsbc-dh"
- name: SUFFIX
  displayName: "Application name suffix"
  description: "Application name suffix"
  required: true
- name: RABBITMQ_NAME
  description: "Name of the RabbitMQ cluster"
  value: "rabbitmq"
- name: RABBITMQ_USER
  description: "Username for the RabbitMQ instance"
  value: "rabbitmq"
- name: RABBITMQ_PASS
  description: "Password securing the RabbitMQ instance"
  value: "rabbitmq"
- name: DB_USERNAME
  description: "Username for the MS PowerBI db"
  value: "dbuser"
- name: DB_PASSWORD
  description: "Password for the MS PowerBI db"
  value: "dbpass"
