apiVersion: v1
kind: Template
metadata:
  name: rsbcdh-secrets-template
  annotations:
    description: "Create secret object for RSBC DH"
    tags: rabbitmq,mq,messaging
parameters:
- name: NAME
  displayName: "Name"
  description: "The name assigned to all of the OpenShift resources associated to the server instance."
  required: true
  value: rsbc-dh
- name: SUFFIX
  displayName: "Application name suffix"
  description: "Application name suffix"
  required: true
- name: VERSION
  displayName: "Application version number"
  description: "Application version number"
  required: true
- name: PHASE
  displayName: "Application phase"
  description: "Application phase"
  required: true
- name: RABBITMQ_NAME
  description: "Name of the RabbitMQ cluster"
  value: rabbitmq
 name: RABBITMQ_USER
  description: "Username for the RabbitMQ instance"
  value: rabbitmq
- name: RABBITMQ_PASS
  description: "Password securing the RabbitMQ instance"
  generate: expression
  from: "[a-zA-Z0-9]{16}"
objects:
- apiVersion: v1
  kind: Secret
  stringData:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
  metadata:
    name: ${NAME}${SUFFIX}
    annotations:
      as-copy-of: ${NAME}
  type: Opaque
