apiVersion: v1
kind: Template
metadata: {}
parameters:
- name: NAME
- name: COMPONENT
  value: writer
- name: PHASE
- name: SUFFIX
- name: VERSION
- name: HOST
- name: RABBITMQ_URL
- name: MQ_WRITER_USER
- name: MQ_WRITER_PASS
- name: DB_HOST
  required: true
- name: DB_NAME
  required: true
- name: DB_USERNAME
- name: DB_PASSWORD
- name: SECRET_KEY
- name: PYTHONPATH
  value: '/opt/app-root/lib/python3.6/site-packages:/opt/app-root/src/'
- name: URL_SUFFIX
  required: true
- name: CPU_REQUEST
  displayName: Requested CPU
  description: Requested CPU
  required: true
- name: CPU_LIMIT
  displayName: CPU upper limit
  description: CPU upper limit
  required: true
- name: MEMORY_REQUEST
  displayName: Requested memory
  description: Requested memory
  required: true
- name: MEMORY_LIMIT
  displayName: Memory upper limit
  description: Memory upper limit
  required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      shared: "true"
    name: ${NAME}-${COMPONENT}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}-${COMPONENT}${SUFFIX}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 180
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-${COMPONENT}${SUFFIX}
      spec:
        containers:
        - image: " "
          name: app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: RABBITMQ_URL
              value: ${NAME}-rabbitmq${SUFFIX}
            - name: MQ_WRITER_USER
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: username
            - name: MQ_WRITER_PASS
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: password
            - name: DB_HOST
              value: ${DB_HOST}
            - name: DB_NAME
              value: ${DB_NAME}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: db-password
            - name: PYTHONPATH
              value: ${PYTHONPATH}
          resources:
            limits:
              cpu: 80m
              memory: 96Mi
            requests:
              cpu: 60m
              memory: 64Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - app
        from:
          kind: ImageStreamTag
          name: ${NAME}-${COMPONENT}:${VERSION}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: null
    labels: null
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    maxReplicas: 2
    minReplicas: 1
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: ${NAME}-${COMPONENT}${SUFFIX}
    targetCPUUtilizationPercentage: 85
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      deploymentconfig: ${NAME}-${COMPONENT}${SUFFIX}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    host: ${NAME}-${COMPONENT}${SUFFIX}${URL_SUFFIX}
    path: ""
    port:
      targetPort: 5000-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}-${COMPONENT}${SUFFIX}
      weight: 100
    wildcardPolicy: None
