apiVersion: v1
kind: Template
metadata: {}
parameters:
- name: NAME
- name: COMPONENT
  value: paybc
- name: PHASE
- name: SUFFIX
- name: VERSION
- name: HOST
- name: PAYBC_CLIENT_ID
- name: PAYBC_CLIENT_SECRET
- name: PAYBC_FLASK_SECRET
- name: VIPS_API_ROOT_URL
- name: VIPS_API_USERNAME
- name: VIPS_API_PASSWORD
- name: COMM_SERV_AUTH_URL
- name: COMM_SERV_API_ROOT_URL
- name: COMM_SERV_REALM
- name: COMM_SERV_CLIENT_ID
- name: COMM_SERV_CLIENT_SECRET
- name: ADMIN_EMAIL_ADDRESS
- name: BCC_EMAIL_ADDRESSES
- name: AUTHLIB_INSECURE_TRANSPORT
- name: LOG_LEVEL
  value: 'INFO'
- name: FLASK_ENV
  value: 'development'
- name: URL_SUFFIX
  required: true
- name: CPU_REQUEST
  displayName: Requested CPU
  description: Requested CPU
  required: true
- name: CPU_LIMIT
  displayName: CPU upper limit
  description: CPU upper limit
  required: true
- name: MEMORY_REQUEST
  displayName: Requested memory
  description: Requested memory
  required: true
- name: MEMORY_LIMIT
  displayName: Memory upper limit
  description: Memory upper limit
  required: true
objects:
- apiVersion: v1
  kind: Secret
  stringData:
    paybc-client-id: ${PAYBC_CLIENT_ID}
    paybc-client-secret: ${PAYBC_CLIENT_SECRET}
    paybc-flask-secret: ${PAYBC_FLASK_SECRET}
  metadata:
    name: ${NAME}${SUFFIX}
    annotations:
      as-copy-of: template.${NAME}-${PHASE}
  type: Opaque
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      shared: "true"
    name: ${NAME}-${COMPONENT}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${NAME}-${COMPONENT}${SUFFIX}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 180
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-${COMPONENT}${SUFFIX}
      spec:
        volumes:
        - name: "${NAME}-data"
          persistentVolumeClaim:
            claimName: "${NAME}-${COMPONENT}${SUFFIX}"
        containers:
        - image: " "
          name: app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PAYBC_FLASK_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${NAME}${SUFFIX}
                  key: paybc-flask-secret
            - name: PAYBC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ${NAME}${SUFFIX}
                  key: paybc-client-id
            - name: PAYBC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${NAME}${SUFFIX}
                  key: paybc-client-secret
            - name: VIPS_API_ROOT_URL
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: vips-api-root-url
            - name: VIPS_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: vips-api-username
            - name: VIPS_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: vips-api-password
            - name: COMM_SERV_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: comm-serv-auth-url
            - name: COMM_SERV_API_ROOT_URL
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: comm-serv-api-root-url
            - name: COMM_SERV_REALM
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: comm-serv-realm
            - name: COMM_SERV_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: comm-serv-client-id
            - name: COMM_SERV_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: comm-serv-client-secret
            - name: ADMIN_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: admin-email-address
            - name: BCC_EMAIL_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: ${NAME}-${PHASE}
                  key: bcc-email-addresses
            - name: LOG_LEVEL
              value: ${LOG_LEVEL}
            - name: ENVIRONMENT
              value: ${PHASE}
            - name: AUTHLIB_INSECURE_TRANSPORT
              value: "True"
          resources:
            limits:
              cpu: 80m
              memory: 96Mi
            requests:
              cpu: 60m
              memory: 64Mi
          volumeMounts:
          - name: "${NAME}-data"
            mountPath: "/var/lib/sqlite"
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - app
        from:
          kind: ImageStreamTag
          name: ${NAME}-${COMPONENT}:${VERSION}
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: null
    labels: null
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    maxReplicas: 2
    minReplicas: 1
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: ${NAME}-${COMPONENT}${SUFFIX}
    targetCPUUtilizationPercentage: 85
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      deploymentconfig: ${NAME}-${COMPONENT}${SUFFIX}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}-${COMPONENT}${SUFFIX}
  spec:
    host: ${NAME}-${COMPONENT}${SUFFIX}${URL_SUFFIX}
    path: ""
    port:
      targetPort: 5000-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}-${COMPONENT}${SUFFIX}
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "${NAME}-${COMPONENT}${SUFFIX}"
  labels:
    name: "${NAME}-${COMPONENT}${SUFFIX}"
    template: "${NAME}-persistent-template"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "20Mi"

