FROM python:3.7.3-stretch

COPY form_verification/requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

ENV PYTHONPATH /home/appuser/

COPY common/ /home/appuser/python/common/
COPY form_verification/ /home/appuser/python/form_verification/

CMD [ "python", "./python/form_verification/listener.py" ]
