spring:
  application:
    name: pdf-gen-service
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:default}
logging:
    level:
      root: ${LOGGING_LEVEL:INFO}
    structured:
         format:
            console: ecs
adobe:
   ords:
    auth:
      username: ${ADOBEORDS_USER}
      password: ${ADOBEORDS_PASS}
    base_url: ${ADOBEORDS_BASE_URL}
   aem:
      report:
          server:
             url: ${AEM_REPORT_SRV_URL}
             appid: ${AEM_REPORT_SRV_APPID} 
mail:
   it: 
     username: ${MAILIT_USER}
     password: ${MAILIT_PASS}	
     url: ${MAILIT_URL}
     from: ${DO_NOT_REPLY_ADDRESS}
     registry: ${APPEALS_REGISTRY_EMAIL} 
     bcc1: ${EMAIL_BCC1:null}
     bcc2: ${EMAIL_BCC2:null}

security:
   httplistener:
     username: ${HTTP_LISTENER_USER} 
     password: ${HTTP_LISTENER_PASS} 

server:
  port: 8082
