spring:
  application:
    name: pdf-gen-service
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

adobeords:
    auth:
      username: ${ADOBEORDS_USER}
      password: ${ADOBEORDS_PASS}
    base_url: ${ADOBEORDS_BASE_URL}

server:
  port: 8082
