spring:
  application:
    name: pdf-gen-service
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

adobeOrds:
    auth:
      username: yourUsername
      password: yourPassword
    url: https://api.example.com/adobe/save

server:
  port: 8082
