spring:
  application:
    name: pdf-gen-service
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

logging:
    level:
      root: INFO
    structured:
         format:
            console: ecs

org:
  springframework:DEBUG

adobe:
   ords:
    auth:
      username: ${ADOBEORDS_USER}
      password: ${ADOBEORDS_PASS}
    base_url: ${ADOBEORDS_BASE_URL}

   aem:
      report:
          server:
             url: ${AEM_REPORT_SRV_URL}
             config: ${AEM_REPORT_SRV_CONFIG} 
mail:
   it: 
     username: ${MAILIT_USER}
     password: ${MAILIT_PASS}	
     url: ${MAILIT_URL}
     from: ${DO_NOT_REPLY_ADDRESS}
     registry: ${APPEALS_REGISTRY_EMAIL} 
     bcc1: ${EMAIL_BCC1:null}
     bcc2: ${EMAIL_BCC2:null}
            
server:
  port: 8082
