name: ci-workflow

on:
  workflow_call:
    inputs:
      docker-context:
        required: true
        type: string
      docker-file:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.docker-file }}
          push: false
