name: form-handler-ci

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - python/*.py
      - python/common
      - python/form_handler
      - .github/workflows/form-handler-ci.yml

jobs:
  call-workflow-passing-data:
    uses: ytqsl/RSBC-DataHub-API/.github/workflows/ci-workflow.yml@master
    with:
      docker-context: python
      docker-file: python/form_handler/Dockerfile
