name: form-handler-ci

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - python/*.py
      - python/common
      - python/form_handler
      - .github/workflows/form-handler-ci.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: python
          file: python/form_handler/Dockerfile
          push: false
