name: form-handler-ci

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - python/common
      - python/form_handler
      - .github/workflows/form-handler-ci.yml

env:
  IMAGE_NAME: form-handler
  WORKING_DIR: python
  DOCKER_FILE: form-handler/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Build image
        working-directory: ${{ env.WORKING_DIR }}
        run: docker build -f $DOCKER_FILE --tag $IMAGE_NAME .
