name: form_handler-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - python/*.py
      - python/common
      - python/form_handler
      - .github/workflows/form_handler-ci.yml

jobs:
  CI:
    uses: ytqsl/RSBC-DataHub-API/.github/workflows/ci-workflow.yml@master
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/form_handler/Dockerfile
