name: geocodersvc-ci

on:
  # push:
  #   branches_ignore:
  #     - master
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches-ignore:
      - master
    paths:
      - python/*.py
      - python/common/**
      - python/geocodersvc/**
      - .github/workflows/geocodersvc-ci.yml
      - trigger.txt

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/geocodersvc/Dockerfile
