name: geocodersvc-cd

on:
  push:
    branches:
      - master
    paths:
      - python/*.py
      - python/common
      - python/geocodersvc
      - .github/workflows/geocodersvc-cd.yml

jobs:
  CI:
    uses: ytqsl/RSBC-DataHub-API/.github/workflows/cd-workflow.yml@master
    with:
      docker-context: python
      docker-file: python/geocodersvc/Dockerfile
      docker-image-name: dh-geocodersvc
