name: geocodersvc-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - python/*.py
      - python/common
      - python/geocodersvc
      - .github/workflows/geocodersvc-ci.yml

jobs:
  CI:
    uses: ytqsl/RSBC-DataHub-API/.github/workflows/ci-workflow.yml@master
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/geocodersvc/Dockerfile
