name: ingestor-cd

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
    paths:
      - python/*.py
      - python/common/**
      - python/ingestor/**
      - .github/workflows/ingestor-cd.yml
      - trigger.txt

jobs:
  CD:
    uses: ./.github/workflows/cd-workflow.yml
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/ingestor/Dockerfile
      DOCKER_IMAGE_NAME: dh-ingestor
    secrets: inherit
