name: ingestor-cd

on:
   push:
    branches:
      - master
    paths:
      - python/*.py
      - python/common
      - python/ingestor
      - .github/workflows/ingestor-cd.yml

jobs:
  CI:
    uses: ytqsl/RSBC-DataHub-API/.github/workflows/cd-workflow.yml@master
    with:
      docker-context: python
      docker-file: python/ingestor/Dockerfile
      docker-image-name: dh-ingestor
