name: ingestor-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - python/*.py
      - python/common
      - python/ingestor
      - .github/workflows/ingestor-ci.yml

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml@master
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/ingestor/Dockerfile
