name: OWASP ZAP Baseline Scan
on:
  push:
    branches: [master]
  #schedule:
    # Runs every week at 01:00 Sunday Morning.
  #  - cron:  '0 1 * 6 0'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP Test Site
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: "https://rsbc-dh-web-form-prod.apps.silver.devops.gov.bc.ca"
