name: paybc-cd

on:
  # push:
  #   branches:
  #     - master
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
    paths:
      - python/*.py
      - python/common/**
      - python/paybc_api/**
      - .github/workflows/paybc-cd.yml
      - trigger.txt

jobs:
  CD:
    uses: ./.github/workflows/cd-workflow.yml
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/paybc_api/Dockerfile
      DOCKER_IMAGE_NAME: dh-paybc
    secrets: inherit
