name: paybc-cd

on:
  push:
    branches:
      - master
    paths:
      - python/*.py
      - python/common
      - python/paybc_api
      - .github/workflows/paybc-cd.yml

jobs:
  CI:
    uses: ./.github/workflows/cd-workflow.yml
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/paybc_api/Dockerfile
      DOCKER_IMAGE_NAME: dh-paybc
    secrets: inherit
