name: rsbc-dh-claimav-ci

on:
  push:
    branches:
      - feature/apr-43

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
    with:
      DOCKER_CONTEXT: Java/clamav_client
      DOCKER_FILE: Java/clamav_client/Dockerfile
