name: rsbc-dh-claimav-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches-ignore:
      - master
    paths:
      - Java/clamav_client/**
      - trigger.txt

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
    with:
      DOCKER_CONTEXT: Java/clamav_client
      DOCKER_FILE: Java/clamav_client/Dockerfile
