name: rsbc-dh-claimav-cd

on:
  push:
    branches:
      - 'release/test-workflow'
    paths:
       - "Java/README.md"
       - "Java/clamav_client/**"
       - ".github/workflows/rsbh-dh-clamav-*.yml"
env:
  DOCKER_FILE: Java/clamav_client/Dockerfile
  DOCKER_IMAGE_NAME: dh-clamav-client
  WORKING_DIRECTORY: Java/clamav_client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push the image
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
