name: rsbc-dh-web-form-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches-ignore:
      - master
    paths:
      - "Java/README.md"
      - "web_app/**"
      -  ".github/workflows/rsbh-dh-web-form*.yml"

env:
  DOCKER_FILE: web_app/Dockerfile
  DOCKER_IMAGE_NAME: dh-web-form
  WORKING_DIRECTORY: web_app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_BE78D6 }}
          username: ${{ secrets.DOCKER_USERNAME_BE78D6 }}
          password: ${{ secrets.DOCKER_PASSWORD_BE78D6 }}

      - name: Build & Push the image
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY_BE78D6 }}/${{ env.DOCKER_IMAGE_NAME }}:latest .