name: rsbc-dh-claimav-cd

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - master
    paths:
       - "Java/README.md"
       - "Java/clamav_client/**"
       - ".github/workflows/rsbh-dh-clamav-*.yml"

jobs:
  CD:
    uses: ./.github/workflows/cd-workflow-orbeon-replacement.yml
    with:
      DOCKER_CONTEXT: Java/clamav_client
      DOCKER_FILE: Java/clamav_client/Dockerfile
      DOCKER_IMAGE_NAME: dh-clamav-client
    secrets: inherit
