name: rsbc-dh-web-form-cd

on:
  push:
    #    types: [opened, reopened, edited, synchronize]
    branches:
      - 'release/test-workflow'
    paths:
      - "Java/README.md"
      - "web_app/**"
      -  ".github/workflows/rsbh-dh-web-form*.yml"

env:
  DOCKER_FILE: web_app/Dockerfile
  DOCKER_IMAGE_NAME: dh-web-form
  WORKING_DIRECTORY: web_app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push the image
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:latest