name: validator-ci

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches-ignore:
      - master
    paths:
      - python/*.py
      - python/common/**
      - python/validator/**
      - .github/workflows/validator-ci.yml
      - trigger.txt

jobs:
  CI:
    uses: ./.github/workflows/ci-workflow.yml
    with:
      DOCKER_CONTEXT: python
      DOCKER_FILE: python/validator/Dockerfile
